force-app/main/default/objects/sf_devops_Change_Submission__c/sf_devops_Change_Submission__c.object-meta.xml
<CustomObject>
    <label>sf_devops_Change_Submission</label>
    <nameField>
        <label>sf_devops_Change_Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sf_devops_Change_Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sf_devops_Change_Submission__c/fields/sf_devops_Work_Item__c.field-meta.xml
<CustomField>
    <fullName>sf_devops_Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sf_devops_Work_Item</label>
    <referenceTo>sf_devops_Work_Item__c</referenceTo>
    <relationshipLabel>sf_devops_Change_Submissions</relationshipLabel>
    <relationshipName>sf_devops_Change_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sf_devops_Remote_Change__c/sf_devops_Remote_Change__c.object-meta.xml
<CustomObject>
    <label>sf_devops_Remote_Change</label>
    <nameField>
        <label>sf_devops_Remote_Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sf_devops_Remote_Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sf_devops_Remote_Change__c/fields/sf_devops_Change_Submission__c.field-meta.xml
<CustomField>
    <fullName>sf_devops_Change_Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sf_devops_Change_Submission</label>
    <referenceTo>sf_devops_Change_Submission__c</referenceTo>
    <relationshipLabel>sf_devops_Remote_Changes</relationshipLabel>
    <relationshipName>sf_devops_Remote_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sf_devops_Work_Item__c/sf_devops_Work_Item__c.object-meta.xml
<CustomObject>
    <label>sf_devops_Work_Item</label>
    <nameField>
        <label>sf_devops_Work_Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sf_devops_Work_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/QueryWorkItemById.cls
public with sharing class QueryWorkItemById {

    public List <sf_devops_Work_Item__c> getWorkItem (String workId) {

        List <sf_devops_Work_Item__c> Workitem = new List <sf_devops_Work_Item__c> ();

        try {
            Workitem.add([ SELECT Id, Name FROM sf_devops_Work_Item__c WHERE Id =:workId ] ) ;


        } catch (Exception e) {
            

            System.debug('Enter valid Id');
            
        }

        return Workitem ;
       
    }

    public  List <sf_devops_Change_Submission__c > getChangeSubmission (String workItemsId) {

        List <sf_devops_Change_Submission__c> ChangeSubmission = new List  <sf_devops_Change_Submission__c> ();

        try {
            
             ChangeSubmission.add([ SELECT Id, Name FROM sf_devops_Change_Submission__c WHERE sf_devops_Work_Item__c =: workItemsId])   ;

            
        } catch (Exception e) {

            System.debug('Enter valid WorkItemId');
            
        }

        return ChangeSubmission ;

    }

    public  List < sf_devops_Remote_Change__c> getRemoteChange (List<String> changeSubmissionsId ) {

        List < sf_devops_Remote_Change__c> RemoteChange = new List < sf_devops_Remote_Change__c>();

        try {


            RemoteChange.add([ SELECT Id, Name FROM sf_devops_Remote_Change__c WHERE sf_devops_Change_Submission__c IN : changeSubmissionsId]) ;


        } catch (Exception e) {

            System.debug('Enter valid changeSubmissionsId');
            
        }

        return  RemoteChange ;
    }

    public  void main (String workItemId ) {
            List <sf_devops_Work_Item__c> Workitem = getWorkItem(workItemId);
            List <sf_devops_Change_Submission__c> ChangeSubmission = getChangeSubmission(workItemId);
            List<String> Ids = new List<String>();
            for (sf_devops_Change_Submission__c i : ChangeSubmission){
                Ids.add(i.Id);
                }  
            List < sf_devops_Remote_Change__c> RemoteChange = getRemoteChange(Ids);
            delete RemoteChange;
            delete ChangeSubmission;
            delete Workitem; 

    }

}