force-app/main/default/objects/sf_devops_Change_Submission__c/sf_devops_Change_Submission__c.object-meta.xml
<CustomObject>
    <label>sf_devops_Change_Submission</label>
    <nameField>
        <label>sf_devops_Change_Submission Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sf_devops_Change_Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sf_devops_Change_Submission__c/fields/sf_devops_Work_Item__c.field-meta.xml
<CustomField>
    <fullName>sf_devops_Work_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sf_devops_Work_Item</label>
    <referenceTo>sf_devops_Work_Item__c</referenceTo>
    <relationshipLabel>sf_devops_Change_Submissions</relationshipLabel>
    <relationshipName>sf_devops_Change_Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sf_devops_Remote_Change__c/sf_devops_Remote_Change__c.object-meta.xml
<CustomObject>
    <label>sf_devops_Remote_Change</label>
    <nameField>
        <label>sf_devops_Remote_Change Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sf_devops_Remote_Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/sf_devops_Remote_Change__c/fields/sf_devops_Change_Submission__c.field-meta.xml
<CustomField>
    <fullName>sf_devops_Change_Submission__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>sf_devops_Change_Submission</label>
    <referenceTo>sf_devops_Change_Submission__c</referenceTo>
    <relationshipLabel>sf_devops_Remote_Changes</relationshipLabel>
    <relationshipName>sf_devops_Remote_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/sf_devops_Work_Item__c/sf_devops_Work_Item__c.object-meta.xml
<CustomObject>
    <label>sf_devops_Work_Item</label>
    <nameField>
        <label>sf_devops_Work_Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>sf_devops_Work_Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static sf_devops_Work_Item__c createWorkItem () {

        sf_devops_Work_Item__c a1 = new sf_devops_Work_Item__c();
        a1.Name = 'Work Item1';
        insert a1;
        return a1;

    }

    public static sf_devops_Change_Submission__c createChangeSubmission () {

        sf_devops_Change_Submission__c b1 = new  sf_devops_Change_Submission__c() ;
        b1.name = 'Change Submission 1';
        insert b1;
        return b1;
    }

    public static  sf_devops_Remote_Change__c createRemoteChange () {

        sf_devops_Remote_Change__c c1 = new sf_devops_Remote_Change__c();
        c1.name = 'Remote  Change 1';
        insert c1;
        return c1;
    }

    @isTest
    public void myUnitTest(){

        sf_devops_Work_Item__c a1 = TestDataFactory.createWorkItem();
        sf_devops_Work_Item__c d1 = QueryWorkItemById.getWorkItem(a1.id);
        sf_devops_Change_Submission__c b1 =TestDataFactory.createChangeSubmission();
        b1.sf_devops_Work_Item__c = a1.Id;
        sf_devops_Remote_Change__c c1 = TestDataFactory.createRemoteChange();
        c1.sf_devops_Change_Submission__c = b1.Id;
        QueryWorkItemById handler = new QueryWorkItemById();
        handler.main(a1.Id);

    }
}